name: Code Quality Checks

on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint --if-present || echo "No lint script found"
      
    - name: Check code formatting
      run: npm run format:check --if-present || echo "No format check script found"
      
    - name: Type checking
      run: npm run type-check --if-present || echo "No type check script found"
      
    - name: Security audit
      run: npm audit --audit-level=moderate
      
    - name: Check bundle size
      run: |
        npm run build
        du -sh build/
        find build/static/js -name "*.js" -exec ls -lh {} \;